### ISSUE TITLE
about sort by 

### ISSUE THREAD

**Issue by bigsea00001** [iperov/OpenDeepFaceSwap#10]
I do not know the difference between "blur", "face", "face-dissim", "face-yaw", "hist" and "hist-dissim"
Is there anyone who can explain?

**Comment by Kirin-kun** [comment]
blur is how blurry the face is.
face compares how faces are similar.
face-dissim compares how faces are dissimilar
face-yaw sorts by yaw rotation, ie the direction of the face around a vertical axis (
hist is how color histogram of the faces are similar.
hist-dissim is how color histogram of the faces are dissimilar.

The sort renames the files so they are grouped according to this criteria so you can easily make a face set for training.

Maybe I'd suggest a feature where they could be sorted by expression, open/closed eyes/mouth. Some models could benefit from it.

**Comment by bigsea00001** [comment]
Thank you. Now it seems to be clear ~ !!
