### ISSUE TITLE
Case sensitive parameters

### ISSUE THREAD

**Issue by Kirin-kun** [iperov/OpenDeepFaceSwap#11]
I wrote some cmd scripts with parameters on windows, because your parameters are awfully long, so, I just made an extract.cmd, a train.cmd and a convert.cmd with some %1 %2 and %3 and it's easier to run. One of them is the model name and it seems that this parameter is case sensitive. df gives an error, when DF does not.

Not really a major issue, but I wondered if it's on purpose?

**Comment by Kirin-kun** [comment]
I doubt someone will make a Model_DF and a Model_df

**Comment by iperov** [comment]
My windows build already has all necessary .cmd's
Case sensitive model name is not a problem.

`I doubt someone will make a Model_DF and a Model_df`
then he will be banned
