### ISSUE TITLE
NN Feeder and yaw bias

### ISSUE THREAD

**Issue by Kirin-kun** [iperov/OpenDeepFaceSwap#12]
If I understood correctly, you feed the NN with paired data in term of yaw. For each dst face, you find the most similar yaw faces in src and feed them to the NN.

I have in my src data some 3/4 view faces, with eyes closed and open mouth, so I thought it would be nice because in my dst there are a lot of closed eyes and open mouth. But dst face is always looking straight at the camera.

So, when I refresh the preview, I never see the faces with closed eyes, open mouth. They don't seem to be ever used for training because their yaw is too far from the dst.

I hit [p] several times, but I never see the closed eyes faces in the preview. Is it expected?

In original, these faces were used for training. I think, maybe, your NN feeder introduces bias toward the yaw, which would explain a little the **problems with mouth and eyes.**

**Comment by Kirin-kun** [comment]
A face like this (random google image) 
![stock-photo-young-woman-with-beautiful-makeup-face-close-up-eyes-closed-129445544](https://user-images.githubusercontent.com/36699120/39084698-b413b264-4579-11e8-9d2a-00de8f525e2c.jpg)

Will never be used if dst doesn't contain close enough yaw face, so the features will never be learned/averaged? Or did I misunderstand.

**Comment by Kirin-kun** [comment]
And I made a real clean src faceset with only 96 images, so I should have seen those face quickly. But they never showed up.

**Comment by iperov** [comment]
Just compare result with faceswap/fakeapp.

**Comment by iperov** [comment]
also you can do train with `--debug` and check all images which will be feeded into nn

**Comment by iperov** [comment]
download last commit and train with --debug

**Comment by Kirin-kun** [comment]
I made training test debug, with only 2 faces in src.

1 looking sideways, 1 other face looking face camera.

The training debug showed ONLY the face camera face, changing a bit each time I press [p]. Because in dst, face is only looking forward. In dst, there are 1500 faces, all looking at the camera.

Your feeder totally ignored the other faces. It only uses it if it's the only one.

It's easy to reproduce:

src:
![cudna13_0](https://user-images.githubusercontent.com/36699120/39086156-d9c77842-458d-11e8-95a6-98e4e8243c25.png)
![cudna07_0](https://user-images.githubusercontent.com/36699120/39086166-f98bff5e-458d-11e8-859c-dfd9e7f8abeb.png)

dst:
![gamer0047_0](https://user-images.githubusercontent.com/36699120/39086042-2890fb94-458c-11e8-9d41-30eaf692f95d.png)

First image never appears in debug. Only the second one. 

So, the NN can never learn mouth and eyes of these faces. Your feeder introduces bias into features the NN learns.

Original learns them.

**Comment by iperov** [comment]
Autoencoder just averages faces.
So for your dst face there is only second src best matching dst face. Why learn useless faces?
Gather more src faces.

There is no method how to detect closed eyes.

**Comment by Kirin-kun** [comment]
In my case, src face is a person for which I only have a few hundred pictures (not the person above). 

Out of these, I have very few pictures with closed eyes and open mouth.

So, either I take one good picture with closed eyes and copy it 100 times, or I use Original because it's better suited to that case, since it learns all faces.

**Comment by Kirin-kun** [comment]
https://www.researchgate.net/post/How_can_I_determine_if_the_detected_eyes_are_open_or_closed

**Comment by iperov** [comment]
` I use Original because it's better suited to that case, since it learns all faces.`
also it learns 1000 similar faces of front yaw and 1 face of side yaw as result of irregular training.

**Comment by iperov** [comment]
@Kirin-kun go ahead and implement it

**Comment by iperov** [comment]
even with smart yaw feeder, side face learns not so quickly as frontal faces

![python_2018-04-21_21-03-23](https://user-images.githubusercontent.com/8076202/39086735-e1e7ec18-45a7-11e8-80e0-374d9274f569.jpg)

**Comment by Kirin-kun** [comment]
Maybe because there's not enough Trump side faces. Original has same problem. It would be worth a shot to try to put more side faces than frontal faces in both facesets to see if it learns side face faster than frontal face.

But the pretrained NN has be trained with frontal faces anyway.

But Original has less problems with eyes and mouth.

**Comment by Kirin-kun** [comment]
Well, that was informative. I think it explains why OpenDeepFaceSwap, at least in my case, showed open eyes and closed mouth in conversion, even if dst has closed eyes and open mouth. It's more sensitive to the facesets than Original. I compared with faceswap and because of that I get better result.

I'll close this.

**Comment by iperov** [comment]
Of course it learns faster.
If we not feed side face for a time, NN forgives it.

**Comment by iperov** [comment]
its just problem of autoencoder. Need better models.

IAE recognize closed eyes:

![python_2018-04-21_21-19-51](https://user-images.githubusercontent.com/8076202/39086969-35147490-45aa-11e8-9282-d7969508c411.jpg)

vs DF:

![python_2018-04-21_21-03-23](https://user-images.githubusercontent.com/8076202/39086970-36ecf7e2-45aa-11e8-900b-55d8e821192c.jpg)

so why we need to adjust faceset to suxx original model ? :)

**Comment by iperov** [comment]
also detect closed eyes of chinesse face or Trump is impossible.
NN must detect it and reconstructs properly.

**Comment by Kirin-kun** [comment]
That's what I was thinking too. IAE stores expressions in separate layers. But it give weird faces :/

**Comment by iperov** [comment]
last column - ABxAB layer
![python_2018-04-21_22-33-08](https://user-images.githubusercontent.com/8076202/39087604-6e90809c-45b4-11e8-9420-5563ee2e41a9.jpg)

**Comment by iperov** [comment]
"Lighter IAEF"
![2018-04-22_09-47-50](https://user-images.githubusercontent.com/8076202/39091989-ad892214-4612-11e8-9f12-371095653fd4.jpg)

**Comment by iperov** [comment]
I will test with usual feeder without yaw sorter

**Comment by iperov** [comment]
I found lighter IAE much better, its not same as DF(original), but not so hard morphing to dst, something between them.

**Comment by Kirin-kun** [comment]
Maybe add an option to disable it and feed random faces instead of best yaw matches. So depending on the faceset, the user can choose.

**Comment by iperov** [comment]
looks like it sucks
side faces trains normally
![python_2018-04-22_11-43-13](https://user-images.githubusercontent.com/8076202/39092605-d002c6be-4622-11e8-8bc1-ced6f38fac15.jpg)

**Comment by iperov** [comment]
I will remove it.

**Comment by Kirin-kun** [comment]
Thx. I hope it trains better without it, for side faces.

**Comment by Kirin-kun** [comment]
Since you removed the yaw feeder, this issue can be closed.
