### ISSUE TITLE
Error : Unhandled exception in thread started by

### ISSUE THREAD

**Issue by bigsea00001** [iperov/OpenDeepFaceSwap#15]
I am testing with the last commit version and I am getting the following error:

python main.py --tf-suppress-std train --training-data-sr
c-dir faceA --training-data-dst-dir faceB --model-dir models --model IAEF128 --w
rite-preview-history
Running trainer.

Loading model...
Unhandled exception in thread started by

**Comment by iperov** [comment]
try without --tf-suppress-std

**Comment by bigsea00001** [comment]
There is one more question. If I use the --debug option on the train, nothing happens in the message below (I can see the Training preview window and it also stops):

Starting. Press "Enter" to stop training and save model.

**Comment by iperov** [comment]
debug just for check samples

**Comment by bigsea00001** [comment]
ok...I see
