### ISSUE TITLE
Weird training results

### ISSUE THREAD

**Issue by Sonofdemoc** [iperov/OpenDeepFaceSwap#22]
My training results are weird. Especially the eyes are unusual.

Are other people okay with that?

If so, are my training results odd because there are problems with data_src,dst?
But there was no problem when I trained at faceswap.

Faceswap Preview (original, batch 32, loss_A: 0.02025, loss_B: 0.02348, 15,000 epoch)
![image](https://user-images.githubusercontent.com/19576122/39529066-c1895a1c-4e60-11e8-97fb-b039fc3ecc42.png)

OpenDeepFaceSwap Preview (H64, batch 32, loss_src: 0.02856, loss_dst: 0.02550, 32,000 epoch)
![image](https://user-images.githubusercontent.com/19576122/39529295-42a12dfa-4e61-11e8-857a-f57fc453b24c.png)

Original convert(frame 074):
![image](https://user-images.githubusercontent.com/19576122/39529765-692e5a82-4e62-11e8-9569-b3f3ca32239a.png)

H64 convert(frame 074):
![image](https://user-images.githubusercontent.com/19576122/39529784-76736b2e-4e62-11e8-95ec-d840c99ebd2d.png)

the original has a better result(with decent eye) than h64 at the same epoch(even double). 
Is this normal?

I've tested with " H64 " and " DF " and both eyes are weird.

Please check.
http://sendanywhe.re/779I9ANI

**Comment by iperov** [comment]
OK I will train it on my new H64 and check.

**Comment by iperov** [comment]
![000074](https://user-images.githubusercontent.com/8076202/39559091-bfc3bf08-4ea4-11e8-85ee-a38eac31d382.png)

**Comment by iperov** [comment]
looks like you trained faceswap with other src dataset, because averaged lips differents

**Comment by iperov** [comment]
will check with different warper

**Comment by iperov** [comment]
![python_2018-05-04_00-13-08](https://user-images.githubusercontent.com/8076202/39600477-ec63365c-4f2f-11e8-9cb3-bfe548c93e6c.jpg)

**Comment by Sonofdemoc** [comment]
You get the same result as I do. Is there a problem with the training process? Why is the result worse than the faceswap?

**Comment by iperov** [comment]
nothing problem. H64 is identical to faceswap in last screen.

**Comment by Sonofdemoc** [comment]
identical? ... but it's obviously...

The purpose of this refactoring is to exceed the faceswap. Isn't it?
Clearly there is a problem with the training process.
I am not attacking or complaining. 
I just hope your project beats faceswap.

If you don't want to fix it, don't fix it.
People will use faceswaps as you say.

**Comment by iperov** [comment]
yep, use faceswap.

**Comment by iperov** [comment]
Training process identical to faceswap result last screen. Its averages all faces. 
So my result is more precisely.

Of course my repo better than faceswap. If you dont agree - use faceswap then. Or fakeapp. Or dfaker. Or shaonlu.

**Comment by Sonofdemoc** [comment]
Src face
![00012](https://user-images.githubusercontent.com/19576122/39616964-cf4d7210-4fb8-11e8-877a-c0d3a205607b.jpg)
Dst face
![000074_0](https://user-images.githubusercontent.com/19576122/39616982-def57abe-4fb8-11e8-92c0-ba2579beed29.jpg)

faceswap convert
![image](https://user-images.githubusercontent.com/19576122/39616769-040ec248-4fb8-11e8-8b0d-fd98ea0d78d7.png)

this repo convert
![image](https://user-images.githubusercontent.com/19576122/39616778-0e988668-4fb8-11e8-99e6-a03e93115ed2.png)

your job
![39559091-bfc3bf08-4ea4-11e8-85ee-a38eac31d382_0](https://user-images.githubusercontent.com/19576122/39616751-ed5a6548-4fb7-11e8-977b-aacdbcc10d76.png)
![39600477-ec63365c-4f2f-11e8-9cb3-bfe548c93e6c_0](https://user-images.githubusercontent.com/19576122/39616757-f44ad540-4fb7-11e8-95ac-b46793db1eee.jpg)


I'm not going to use a faceswap. You are a smart guy. I believe you can solve. Look at the result with open mind.

**Comment by iperov** [comment]
nothing to solve anymore. Its final result.

**Comment by iperov** [comment]
use source faces from videos, not photos.

**Comment by Sonofdemoc** [comment]
It wouldn't be bad to bring the traing method of face swap. Think again later. 

Thank you for dealing with me! have a nice day
