### ISSUE TITLE
Exception when training any model besides H64/H128

### ISSUE THREAD

**Issue by mscott8913** [iperov/OpenDeepFaceSwap#24]
$python --version
python version: 3.6.5

$pip3.6 list
Package                 Version    
----------------------- -----------
absl-py                 0.1.12     
astor                   0.6.2      
beautifulsoup4          4.6.0      
bleach                  1.5.0      
bs4                     0.0.1      
certifi                 2017.7.27.1
chardet                 3.0.4      
click                   6.7        
cycler                  0.10.0     
decorator               4.1.2      
Django                  1.11.6     
django-tables2          1.14.2     
dlib                    19.10.0    
enum34                  1.1.6      
face-recognition        1.2.1      
face-recognition-models 0.3.0      
gast                    0.2.0      
gevent                  1.2.2      
greenlet                0.4.12     
grequests               0.3.0      
grpcio                  1.10.0     
h5py                    2.7.1      
html5lib                0.9999999  
idna                    2.6        
ipython                 6.2.1      
ipython-genutils        0.2.0      
jedi                    0.11.0     
Jinja2                  2.9.6      
Keras                   2.1.6      
keras-contrib           2.0.8      
keras-vggface           0.5        
lxml                    4.1.0      
Markdown                2.6.11     
MarkupSafe              1.0        
matplotlib              2.1.2      
networkx                2.1        
numexpr                 2.6.4      
numpy                   1.14.2     
opencv-python           3.3.0.10   
pandas                  0.20.3     
parso                   0.1.0      
pathlib                 1.0.1      
pexpect                 4.2.1      
pickleshare             0.7.4      
Pillow                  5.0.0      
pip                     10.0.1     
playsound               1.2.2      
prompt-toolkit          1.0.15     
protobuf                3.5.1      
ptyprocess              0.5.2      
Pygments                2.2.0      
pyparsing               2.2.0      
python-dateutil         2.6.1      
pytz                    2017.3     
PyWavelets              0.5.2      
PyYAML                  3.12       
requests                2.18.4     
scandir                 1.6        
scikit-image            0.13.1     
scipy                   1.0.0      
selenium                3.6.0      
setuptools              39.0.1     
simplegeneric           0.8.1      
simplejson              3.11.1     
six                     1.11.0     
tables                  3.4.2      
tensorboard             1.6.0      
tensorflow-gpu          1.5.0      
tensorflow-tensorboard  1.5.1      
termcolor               1.1.0      
tqdm                    4.19.5     
traitlets               4.3.2      
urllib3                 1.22       
wcwidth                 0.1.7      
webencodings            0.5.1      
Werkzeug                0.14.1     
wheel                   0.30.0     
xvfbwrapper             0.2.9 

$screenfetch
![screenshot_2018-04-20_05-52-01](https://user-images.githubusercontent.com/30412666/39662873-710f57b0-502e-11e8-89dd-f590ca356786.png)

I do not get errors when training with H64 or H128 but when I try to train with DF, LIAEF128 or MIAEF128 I get the exception:

$ python3.6 main.py train --training-data-src-dir input_extracts_in --training-data-dst-dir input_extracts_out --model-dir models_out --model DF --write-preview-history --multi-gpu --force-gpu-idxs 0,1,2

cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:5880: error: (-215) src.cols > 0 && src.rows > 0 in function warpAffine

[Full error output](https://pastebin.com/2gBUrK3K)

Note: The training does not close out but you can see that it's halted. I have to kill the process with ctrl+c.

**Comment by iperov** [comment]
can you upload our training aligned images

**Comment by iperov** [comment]
but wait. I will commit fix with logging name of sample

**Comment by iperov** [comment]
check last commit and upload problem sample plz

**Comment by mscott8913** [comment]
I deleted some images that were not showing proper faces and updated to latest commit. DF training seems to be going smoothly now. Will keep you posted.

**Comment by iperov** [comment]
this is very bad. I need samples which generates error.

**Comment by iperov** [comment]
but may be last commit fixed it anyway

**Comment by babilio** [comment]
Hi! Thanks for the repo it has become the best deepfake one.

I am still getting this error with LIAEF128 model with the latest pull. You can find src and dst dirs that result in error in this link

https://drive.google.com/drive/folders/16w5zV3LwN7JbLmY5OmiqKNZ_9h47AnUm?usp=sharing

Thank you

**Comment by iperov** [comment]
fixed, check last commit
