### ISSUE TITLE
Extract with --dlib option fails,  AttributeError: module 'dlib' has no attribute 'cuda' 

### ISSUE THREAD

**Issue by gessyoo** [iperov/OpenDeepFaceSwap#28]
## Expected behavior
I wanted to compare the extraction accuracy of --mt vs. --dlib on a video clip

## Actual behavior
Extract with --dlib option fails,  AttributeError: module 'dlib' has no attribute 'cuda' 
Extract with --mt option works as expected, training works as expected with DF and other models tested, conversion works as expected.

## Steps to reproduce
python main.py extract --input-dir C:\input --output-dir C:\output --detector dlib
Error message:
AttributeError: module 'dlib' has no attribute 'cuda'
Also says "You have no capable GPU, try to close programs that use VRAM" etc. 

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)** python main.py extract --input-dir C:\input --output-dir C:\output --detector dlib
- **Operating system and version:** Windows 10 x64 
- **Python version:**  Anaconda 3.6.4
- **Faceswap version:**  latest
- **Faceswap method:** GPU,  Nvidia 1070,  Dlib and opencv compiled with CUDA 9.0 
- **Other related issues:
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by iperov** [comment]
Your dlib built without cuda.

You can use prebuilt binaries for windows, download it from main page

**Comment by iperov** [comment]
run python console
and type:

![cmd_2018-05-10_19-40-50](https://user-images.githubusercontent.com/8076202/39878702-0d2e4de0-548a-11e8-887e-3710a268812c.jpg)

if false - your dlib without CUDA

**Comment by gessyoo** [comment]
Thanks, I couldn't recall the python command to check.  When I run dlib.DLIB_USE_CUDA in python environment, result is "True."  But still the error with --detector dlib.  --detector mt works fine.

**Comment by iperov** [comment]
`module 'dlib' has no attribute 'cuda'`
is mean only dlib compiled without cuda.
This is not repo error. Check your build.

**Comment by LordOEQJen** [comment]
Are you running the script within a virutalenv ?

I would make a new one and do following steps:
-- pip install -r requirements-gpu-python36-cuda9.txt 	
-- pip uninstall dlib
-- Download last dlib version from github or webpage
-- dir to unzipped dlib directory and "python setup.py install --yes DLIB_USE_CUDA"

Also: Got cudnn installed ?
