### ISSUE TITLE
repo error

### ISSUE THREAD

**Issue by andenixa** [iperov/OpenDeepFaceSwap#33]
It seems that the recent repo is missing `__init__.py` at `OpenDeepFaceSwap/utils/`

**Comment by gessyoo** [comment]
I'm a python beginner, but I've been using both the scripts here and more recently, the pre-built Windows binaries in the repo to extract, sort by face, blur, etc., train and convert, without fatal errors under Win 10 x64.  Are you getting an error message while running a command that points to a missing  __init__py?

**Comment by andenixa** [comment]
No I am running `main.py` from a cloned OpenDeepFaceSwap repo and it says:
```Python3
ImportError: No module named utils
```
I looked at `OpenDeepFaceSwap/utils/` dir and its missing `__init__.py` indicating its not a package and can not be imported.

**Comment by iperov** [comment]
@andenixa python version ?

**Comment by andenixa** [comment]
@iperov CPython 3.6 x64

**Comment by andenixa** [comment]
ou aright it might be the Python version anyhow.
