### ISSUE TITLE
Failed to load TensorFlow runtime

### ISSUE THREAD

**Issue by deepfaceswap12345** [iperov/OpenDeepFaceSwap#34]
## Expected behavior

Can't launch the training with the new packages installed.

## Actual behavior

Running trainer.

Loading model...
Error: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

## Steps to reproduce

ran this:
pip install -r .\requirements-gpu-cuda9-cudnn7.txt
and it installed / upgraded all the needed packages, tried again, no errors:

Requirement already satisfied: pathlib==1.0.1 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 1))
Requirement already satisfied: scandir==1.6 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 2))
Requirement already satisfied: h5py==2.7.1 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 3))
Requirement already satisfied: Keras==2.1.6 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 4))
Requirement already satisfied: opencv-python==3.4.0.12 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 5))
Requirement already satisfied: tensorflow-gpu==1.8.0 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: scikit-image in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 7))
Requirement already satisfied: dlib==19.10.0 in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 8))
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from -r .\requirements-gpu-cuda9-cudnn7.txt (line 9))
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from h5py==2.7.1->-r .\requirements-gpu-cuda9-cudnn7.txt (line 3))
Requirement already satisfied: numpy>=1.7 in c:\programdata\anaconda3\lib\site-packages (from h5py==2.7.1->-r .\requirements-gpu-cuda9-cudnn7.txt (line 3))
Requirement already satisfied: scipy>=0.14 in c:\programdata\anaconda3\lib\site-packages (from Keras==2.1.6->-r .\requirements-gpu-cuda9-cudnn7.txt (line 4))
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from Keras==2.1.6->-r .\requirements-gpu-cuda9-cudnn7.txt (line 4))
Requirement already satisfied: tensorboard<1.9.0,>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: grpcio>=1.8.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: gast>=0.2.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: termcolor>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: protobuf>=3.4.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: astor>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: absl-py>=0.1.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: networkx>=1.8 in c:\programdata\anaconda3\lib\site-packages (from scikit-image->-r .\requirements-gpu-cuda9-cudnn7.txt (line 7))
Requirement already satisfied: PyWavelets>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-image->-r .\requirements-gpu-cuda9-cudnn7.txt (line 7))
Requirement already satisfied: pillow>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-image->-r .\requirements-gpu-cuda9-cudnn7.txt (line 7))
Requirement already satisfied: werkzeug>=0.11.10 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: html5lib==0.9999999 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: bleach==1.5.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: markdown>=2.6.8 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf>=3.4.0->tensorflow-gpu==1.8.0->-r .\requirements-gpu-cuda9-cudnn7.txt (line 6))
Requirement already satisfied: decorator>=4.1.0 in c:\programdata\anaconda3\lib\site-packages (from networkx>=1.8->scikit-image->-r .\requirements-gpu-cuda9-cudnn7.txt (line 7))

## Other relevant information
- **Operating system and version:** Windows 10 64 bit
- **Python version:** 3.6.4
- **Faceswap version:** 3986d68cf09884001241055b2f726676297ed77c
- **Faceswap method:** GPU

**Comment by LordOEQJen** [comment]
What CPU are your running ? It needs to support AVX I guess

**Comment by deepfaceswap12345** [comment]
It's exactly on the same machine that was running the previous version and I've been training a lot on this system already.

I've upgraded pip and installed ipykernel as required:

notebook 5.4.0 requires ipykernel, which is not installed.
jupyter 1.0.0 requires ipykernel, which is not installed.
jupyter-console 5.2.0 requires ipykernel, which is not installed.
ipywidgets 7.1.1 requires ipykernel>=4.5.1, which is not installed.
tensorflow 1.6.0 has requirement tensorboard<1.7.0,>=1.6.0, but you'll have tensorboard 1.8.0 which is incompatible.

but after that the last piece remains:
tensorflow 1.6.0 has requirement tensorboard<1.7.0,>=1.6.0, but you'll have tensorboard 1.8.0 which is incompatible.

I removed tesnsorflow 1.6 and kept 1.8 only. Now I don't get any errors when trying the install but when launching the training, same thing:

Loading model...
Error: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

**Comment by iperov** [comment]
You need to upgrade CUDA to 9.0 and cudnn to 7.0.

**Comment by iperov** [comment]
or you can use standalone prebuilt windows binary :)

**Comment by LordOEQJen** [comment]
`tensorflow 1.6.0 has requirement tensorboard<1.7.0,>=1.6.0, but you'll have tensorboard 1.8.0 which is incompatible.`

Aren't you working in an virtualenv ?

**Comment by deepfaceswap12345** [comment]
I thought I was, so I started from the beginning (I've been using Anaconda)

conda create -n tensorflow pip python=3.6.4
activate tensorflow
pip install --ignore-installed --upgrade tensorflow-gpu (which gets me 1.8)

I check and make sure it's there:
conda env list
# conda environments
#

base            *   C:\ProgramData\Anaconda3
tensorflow  *   C:\ProgramData\Anaconda3\envs\tensorflow

then I do a:
pip install -r .\requirements--gpu-cuda9-cudnn.txt

and get a "requirement already satisfied" for all the packages

and yet a train gets me the same "Failed to load the native TensorFlow runtime" error.

**Comment by deepfaceswap12345** [comment]
yes, it's been installed since the very beginning, I've been doing a lot of training before on this system before, with your previous commits and with faceswap as well

**Comment by gessyoo** [comment]
I have a setup like yours, Anaconda 3.64, and am training with the scripts.  Try this script to diagnose the TF issues:  https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c.  

The main difference between the current repro and the past repro is TF 1.8, which needs an AVX-capable CPU, CUDA to 9.0 and cudnn to 7.0.  Per google, "Failed to load the native TensorFlow runtime" error can mean that  your CPU does not have AVX instructions (AVX is found in Intel Sandy Bridge (2011) or newer, or AMD Ryzen).  If you've installed CUDA to 9.0 and cudnn to 7.0, did you add the libraries paths to your path environment, per the link LordOEQJen's post?

**Comment by deepfaceswap12345** [comment]
I think it's the right path:
![image](https://user-images.githubusercontent.com/36651541/40156148-403d6004-595d-11e8-92d5-a69a3bb27786.png)

The script looks for cudart64_80.dll and my .dll version is cudart64_90.dll
Same thing for cudnn64_5.dll where I have cudnn64_7.dll

**Comment by deepfaceswap12345** [comment]
I'm going in parallel with @iperov 's standalone prebuilt windows binary from the torrent, I'll see if that works better

**Comment by iperov** [comment]
> The main difference between the current repro and the past repro is TF 1.8, which needs an AVX-capable CPU, CUDA 9.0 and cudnn 7.0

My tensorflow-gpu==1.8.0 not compiled with AVX2

```
2018-05-17 17:33:36.573458: I T:\src\github\tensorflow\tensorflow\core\platform\
cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow bi
nary was not compiled to use: AVX2
```

**Comment by gessyoo** [comment]
iperov, TF 1.8 has AVX instructions as a requirement (which the developers warn breaks compatibility with older CPUs without AVX) but TF 1.8 doesn't have AVX2 support built-in. You can compile TF from source with option to use AVX2, but I think AVX2 only offers about a 3% improvement in TF vs. AVX.   See https://gist.github.com/kmhofmann/e368a2ebba05f807fa1a90b3bf9a1e03.

**Comment by iperov** [comment]
you mean TF < 1.8.0 doesnt compiled with AVX ?

**Comment by gessyoo** [comment]
Yes, TF < 1.8.0 is not compiled with AVX.  For people with older non-AVX CPUs, recommenced solution is to revert to TF 1.4, which doesn't have AVX requirement.

**Comment by iperov** [comment]
But repo cannot revert to < TF 1.8.0, because only 1.8.0 has new SSIM loss.

**Comment by iperov** [comment]
old version suxx. Better buy avx processor.

**Comment by iperov** [comment]
@gessyoo cool, plz post preview of dst closed eyes at 50k epochs

**Comment by deepfaceswap12345** [comment]
well, if AVX is a must to run the new commit, I think I found why it's not working...
I went to http://masm32.com/board/index.php?topic=3191.0

and I ran the utility that detects it on your CPU (an Intel(R) Core(TM)2 Quad  CPU   Q9300  @ 2.50GHz, 2494 Mhz, 4 Core(s), 4 Logical Processor(s))

and here's my result:
![image](https://user-images.githubusercontent.com/36651541/40215266-1f4ba7fc-5a25-11e8-8919-b81f1a1cfcc8.png)

**Comment by gessyoo** [comment]
deepfaceswap12345, I used a Core2 9400 for several years, good CPU, but a little long in the tooth in 2018.  Ryzen 7 series is good value today, and many other programs besides TF 1.8 (e.g. x264 and x265 and most games), run much faster with AVX instructions and more CPU cores.   TF 1.8 and latest commit here use 12 of 16 Ryzen CPU cores (80%) and about 47% to 55% of Nvidia GPU during training.

**Comment by deepfaceswap12345** [comment]
ok, thanks you all for the help and the advice, I'll switch back to the original faceswap for the time being until I get a newer compatible CPU then
