### ISSUE TITLE
Are the preview images when training showing correctly?

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#37]
## Expected behavior

According to the window it should be Source, Destination, Source -> Destination but that's not what I see.

## Actual behavior

I'm seeing source images in the first 2 columns. The last 3 columns appear to be showing Destination -> Source.

Is this correct behavior?  I expected to see a preview of the source images converting to destination images. Can you explain the columns, if this is correct? Am I doing something wrong? And if it's correct is there a way to get a preview of Src -> Dest?

## Steps to reproduce
python main.py train --training-data-src-dir F:\German --training-data-dst-dir F:\Megyn --model-dir F:\German_Megyn --model H128 --batch-size 32

**Comment by LordOEQJen** [comment]
At first I was confused, too. In fact the sides of dataset_A and B are "switched" compared to the deepfake script. And this makes more sense immo.

First and second picture shows src input (1st Pic) and src output (2nd pic)

3rd and 4th showing the same just for the dst dataset. The 5th shows the swapped face from Src into the "body" of Dst

**Comment by iperov** [comment]
cant help you without screenshot

**Comment by wackyphillwillis** [comment]
https://imgur.com/a/0pGqrVT

**Comment by gessyoo** [comment]
I'm training now with the MIAEF128 model.  The 5th column looks like src image -> dest, at least to my eyes.   https://imgur.com/a/nJ5433r

**Comment by iperov** [comment]
@wackyphillwillis all looks fine on your screenshot. Also your src faces captured by very wide lens.

**Comment by wackyphillwillis** [comment]
@gessyoo Looks dest -> Src to me. The first 2 cols are src then next 2 are dest.

**Comment by gessyoo** [comment]
I'll post a sample of the converted images after 50,000+ epochs or so, probably 24 to 48 hours from now.   But I don't think that the new code is training dst  --> src. even if there is there some issue with the current H128 model.

**Comment by wackyphillwillis** [comment]
@gessyoo I think I just had a different understanding of what src and dst were. I was thinking the src face would be what you transform into the destination face. But it seems to be the src is what you want to be in place of the destination face.

**Comment by wackyphillwillis** [comment]
Is it possible to know what loss number to be shooting for for each model type?

**Comment by gessyoo** [comment]
If you're coming from the original faceswap repro or the FakeApp, the terminology can be confusing.  It used to A=dest. B=celeb, but here, source and destination makes more sense, if you think about it a little.   The old conventional advice was, aim for loss < 0.20 but these models and TF 1.8 use more sophisticated loss calculations, so I'm not sure that advice applies anymore.

**Comment by wackyphillwillis** [comment]
A and B are meaningless but src and dest are not. Typically src would be the input and dest output. Here it's backwards. Because the faces you want for your output must be set as your src. That's backwards to my way of thinking.
