### ISSUE TITLE
Can I see the training image when I am training?

### ISSUE THREAD

**Issue by bigsea00001** [iperov/OpenDeepFaceSwap#4]
Many thanks!! Can I see the training image when I am training as follows?
(batch_size: modified to 2)

https://imgur.com/xLiEDia

**Comment by iperov** [comment]
no training preview window ??

**Comment by bigsea00001** [comment]
H64 has encountered the following error.

https://imgur.com/31s03Wz

**Comment by iperov** [comment]
thx, commited fix

**Comment by bigsea00001** [comment]
Thank you. I run it like the image below ands waiting for the preview window but it is not showing yet.

https://imgur.com/YSIMkVD

**Comment by iperov** [comment]
try one image in aligned src and dst

**Comment by bigsea00001** [comment]
I'm testing one image, but the preview window is still not showing up.

https://imgur.com/5aQNMP6

**Comment by bigsea00001** [comment]
I will be back in 20 minutes.

**Comment by iperov** [comment]
can you install teamviewer ? I will connect to you and check.
Send ID and pin to lepersorium@gmail.com

**Comment by bigsea00001** [comment]
If you do not mind, I will send you an e-mail about TeamViewer tomorrow because I have left the company. This is 1:00 in the morning and I will go to work tomorrow and process it as soon as possible.

**Comment by iperov** [comment]
ok

**Comment by iperov** [comment]
is 'zn' your windows locale ?

**Comment by bigsea00001** [comment]
I think it's KR

**Comment by badluckwiththinking** [comment]
I think I had a similar issue where the training image window does not show if a suitable font file is not found.

```
File "/home/fakes/miniconda3/envs/df/lib/python3.6/site-packages/PIL/ImageFont.py", line 143, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource
```
training ignores the error and continues but without image window

I replaced this line in image_utils.py

```pil_font = get_pil_font(font, size)```

with

```pil_font = ImageFont.load_default()```

Probably a hacky workaround, but at least it make window shows during training now, too bad the font is ugly :)

**Comment by iperov** [comment]
fixed both problem.

@badluckwiththinking what is your locale ? have you Courier New font installed in system?

**Comment by bigsea00001** [comment]
Many thanks to @iperov all problem is fixed. 
I will close this issue.
