### ISSUE TITLE
Extract help mentions '--manual-mode misses' option that seems invalid

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#40]
## Expected behavior
I'd like to only have to manually detect a face for the frames the software fails at. I tried the 'manual-mode misses' option mentioned in the extract help.

## Actual behavior
Command fails:

main.py: error: unrecognized arguments: --manual-mode misses

## Steps to reproduce
python main.py extract --input-dir F:\input --output-dir F:\ouput --detector dlib --manual-mode misses

## Other relevant information
Windows 10
Python 3.6.5

**Comment by iperov** [comment]
I will fix help

proper option is --manual-fix

**Comment by wackyphillwillis** [comment]
OK. --manual-fix seems like it runs for every frame though. Another problem is that the image is not resize the fit the screen. So if your image is larger than your monitor resolution it's really hard/impossible to work with.

**Comment by iperov** [comment]
check last commit
added option --manual-window-size

**Comment by wackyphillwillis** [comment]
OK, I will thanks.
