### ISSUE TITLE
Should images with hands in front of face be removed or included?

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#42]
Assuming the conversion will be using input frames where the person has obstructions like hands in front of their face should these images be included in training or only unobstructed face images for best results?

**Comment by iperov** [comment]
dst faces - any faces you want
src faces - only clear faces

H64/H128 can partially reproduce obstructions
![python_2018-05-18_20-29-03](https://user-images.githubusercontent.com/8076202/40246537-277d95f6-5ada-11e8-9c42-ef26b2613bd2.jpg)

**Comment by wackyphillwillis** [comment]
Thank you!
