### ISSUE TITLE
Batch size and model?

### ISSUE THREAD

**Issue by loldfdfdf** [iperov/OpenDeepFaceSwap#44]
How to change batch size?
Which model is best to use right now?
tank you

**Comment by iperov** [comment]
--batch-size N

depends on task

**Comment by wackyphillwillis** [comment]
I'd be curious how much RAM would be needed for an H256 model.

**Comment by iperov** [comment]
not enough ram even for 128 models

**Comment by wackyphillwillis** [comment]
Then how is it 128 models exist?

**Comment by iperov** [comment]
easy :)
not enough ram mean NN can be better with 12GB ram.

**Comment by wackyphillwillis** [comment]
OK, well 16GB cards should be out in a couple months.

**Comment by iperov** [comment]
for a reasonable price not earlier than 2020 Q2

**Comment by wackyphillwillis** [comment]
I don't care what it costs. I'm talking about what will be available to use. And 16GB should be available in 2 months.

**Comment by iperov** [comment]
> The question was 
where?

**Comment by wackyphillwillis** [comment]
3rd Comment.

**Comment by iperov** [comment]
> I'd be curious how much RAM would be needed for an H256 model.

this is not a question

**Comment by wackyphillwillis** [comment]
OK....
How much RAM would be needed for an H256 model?
