### ISSUE TITLE
Can you add new src/dst images for training?

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#45]
Or do all images need to be added at once so as not to mess up sorting, etc.

**Comment by iperov** [comment]
what you mean 'new src/dst' ?

**Comment by wackyphillwillis** [comment]
After you've  extracted  source and destination images and trained. Can you extract additional images source and destination images and add them to the original ones? Or do all images need to be extracted together?

**Comment by iperov** [comment]
Yes you can.
But dont forget remove added dst faces before convert.

**Comment by wackyphillwillis** [comment]
Are you saying the dst faces used during training should only be from the frames used for the final conversion? Or are you just saying to make sure the input frames for conversion are the right ones?

**Comment by iperov** [comment]
I said enough. You can explore sources for details.
