### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by bigsea00001** [iperov/OpenDeepFaceSwap#47]
How are you? I've been busy a lot and now I'm back again. I'm testing this with the latest version, and I'm getting the following error, I would appreciate your reference.
(This error has not occurred in versions that were completed before May 1.)
============================

J:\__openDeep_face_3\OpenDeepFaceSwap-master>python main.py train --training-dat
a-src-dir faceA --training-data-dst-dir faceB --model-dir models --model MIAEF12
8
Running trainer.

Loading model...
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: C
onversion of the second argument of issubdtype from `float` to `np.floating` is
deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type
`.
  from ._conv import register_converters as _register_converters
2018-05-20 01:38:44.780735: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports inst
ructions that this TensorFlow binary was not compiled to use: AVX
2018-05-20 01:38:44.963746: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 wit
h properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.8475
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 5.71GiB
2018-05-20 01:38:44.964746: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlo
w device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id:
0000:01:00.0, compute capability: 6.1)
Using TensorFlow backend.
Error: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'
Traceback (most recent call last):
  File "J:\__openDeep_face_3\OpenDeepFaceSwap-master\mainscripts\Trainer.py", li
ne 41, in trainerThread
    **in_options)
  File "J:\__openDeep_face_3\OpenDeepFaceSwap-master\models\ModelBase.py", line
114, in __init__
    self.onInitialize(**in_options)
  File "J:\__openDeep_face_3\OpenDeepFaceSwap-master\models\Model_MIAEF128\Model
.py", line 97, in onInitialize
    self.autoencoder_src.compile(optimizer=optimizer, loss=[DSSIMMaskLossClass(s
elf.tf)(mask_layer), 'mse'] )
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", li
ne 830, in compile
    sample_weight, mask)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", li
ne 429, in weighted
    score_array = fn(y_true, y_pred)
  File "J:\__openDeep_face_3\OpenDeepFaceSwap-master\nnlib\__init__.py", line 23
, in __call__
    err = (1.0 - tf.image.ssim (y_true*self.mask, y_pred*self.mask, 1.0)) / 2.0
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'

**Comment by wackyphillwillis** [comment]
Are you running cuda9 & cudnn7?

**Comment by bonlime** [comment]
@bigsea00001 
You can fix it by updating to TF 1.8 Previous versions of simply TF don't have image.ssim function

**Comment by bigsea00001** [comment]
Many thanks to @wackyphillwillis, @bonlime, it works well.
