### ISSUE TITLE
Multigpu not working

### ISSUE THREAD

**Issue by loldfdfdf** [iperov/OpenDeepFaceSwap#48]
I'm trying to use DF model multi-gpu. I have 8 gpu (nvidia tesla K80) but it does not start. 

Gets stuck on "loading model"

Using "best gpu" works but only uses 1 gpu

**Comment by iperov** [comment]
try multi gpu with
--force-gpu-idxs 0,1
--force-gpu-idxs 0,1,2
--force-gpu-idxs 0,1,2,3 .. etc up to 7

**Comment by iperov** [comment]
you can install teamviewer and send invitation to my email lepersorium@gmail.com
I can check issue on your comp.

**Comment by loldfdfdf** [comment]
I got it working, it took very long to load. almost 10 minutes

thank you

**Comment by iperov** [comment]
with 24GB on every card you can boost models to superior quality by increasing conv, dense sizes, and batch sizes

**Comment by iperov** [comment]
this repo designed for mid consumer cards :)

**Comment by loldfdfdf** [comment]
how do i change dense sizes and conv?

**Comment by iperov** [comment]
only by change source :)

**Comment by loldfdfdf** [comment]
no problem. is it complicated or just changing a parameter. can you tell me which one?
