### ISSUE TITLE
Is there any way to change the first preview-history image?

### ISSUE THREAD

**Issue by Jasas9754** [iperov/OpenDeepFaceSwap#49]
--write-preview-history 

This is a very useful feature, but the first preview image remains and becomes obsolete when i try to reuse the model(new src_dst data). Is there any way to change this fixed image when starting a new training session?

**Comment by Jasas9754** [comment]
Can it be added in the future?

**Comment by iperov** [comment]
i dont know. Just restart training and choose preview you need.
