### ISSUE TITLE
'tensorflow.python.ops.image_ops' has no attribute 'ssim'

### ISSUE THREAD

**Issue by Jengall** [iperov/OpenDeepFaceSwap#51]
## Expected behavior

Working :)

## Actual behavior

Error: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'
Traceback (most recent call last):
  File "D:\github\OpenDeepFaceSwap\mainscripts\Trainer.py", line 41, in trainerThread
    **in_options)
  File "D:\github\OpenDeepFaceSwap\models\ModelBase.py", line 116, in __init__
    self.onInitialize(**in_options)
  File "D:\github\OpenDeepFaceSwap\models\Model_DF\Model.py", line 57, in onInitialize
    self.autoencoder_src.compile(optimizer=optimizer, loss=[dssimloss, 'mse'] )
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 860, in compile
    sample_weight, mask)
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 459, in weighted
    score_array = fn(y_true, y_pred)
  File "D:\github\OpenDeepFaceSwap\nnlib\__init__.py", line 43, in __call__
    loss = (1.0 - tf.image.ssim (y_true*mask, y_pred*mask, 1.0)) / 2.0
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'
## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

with your last version I have this error when training a DF model
I am on win10 anaconda 3 and it work like a charm with a 2week old version

Thx a lot for your great job

**Comment by LordOEQJen** [comment]
Did you install the new requirements ? New version is using  updated dependencies

**Comment by iperov** [comment]
install requirements

**Comment by Jengall** [comment]
Sorry, and thx,
Still have a problem "OpenDeepFaceSwap\models\__init__.py" try to import avatar converter line 7 (it doesn't exist anymore)

**Comment by iperov** [comment]
ok

**Comment by Jengall** [comment]
How could i contribute ? should I create my own fork or should I ask you push rights ? (sorry for silly question , i am noob in git)

**Comment by iperov** [comment]
google how to pull request

**Comment by iperov** [comment]
what you want to contrib? better ask before.
I dont want mid-progers which read about patterns and python super features and going to make 3 storey classes from 5 strings of code :D

**Comment by Jengall** [comment]
I made in your sorter, the pitch sort (that works), the eyes aperture sort and the mouth aperture sort.
It s just for help, don't be rude ;)
I am not a mid proger, but as i am noob in python, in git and in open source community, i'll keep my few lines for me ;)

**Comment by iperov** [comment]
whyy ? I dont need such sortings. No models can use it.

**Comment by iperov** [comment]
Sorry but I will decline your pr.

**Comment by Jengall** [comment]
I need it when I create my dataset to make balance between different face configurations.
I like to have my dataset balanced in term of "closed eyes vs opened eyes"   "closed mouth vs opened" "looking up vs looking down", i found it make the model more robust

**Comment by iperov** [comment]
It doesnt help LIAEF128 to recognize closed eyes.

**Comment by iperov** [comment]
Cageset has very small amount faces with closed eyes.
But it is not prevent H128 to recognize closed eyes with 8 batch size.
![h128_cage_0 1](https://user-images.githubusercontent.com/8076202/40440341-db055ce2-5ece-11e8-9726-ad6bf11cfb0c.jpg)

**Comment by Jengall** [comment]
Ok, I made this when you were testing the "closest yaw training"  , and i got really bad results, the mouth and the eyes were very still on the src=>dst (ayes always open, and mouth always closed, even when speaking)
