### ISSUE TITLE
I decided to remove SIAEF128

### ISSUE THREAD

**Issue by iperov** [iperov/OpenDeepFaceSwap#9]
I tested it on Cage/Trump , and nn fell to red previews.

**Comment by Kirin-kun** [comment]
Red preview happened to me also once. It was just after a crash with OOM because I had tried a bigger batch size, so I didn't think about it more and just started a new training. But convert was ugly, with strange eyes and all closed mouths.

IAE seem to be super dependent on the training facesets.

**Comment by bigsea00001** [comment]
I see hope. 
She is now 60,000 epochs, and she seems to be closing her eyes very slowly.
